const CONSTANTS = {
  SOCKET_EVENTS: {
    NEW_MESSAGE: "NEW_MESSAGE",
    NEW_MESSAGE_SUCCESS: "NEW_MESSAGE_SUCCESS",
    NEW_MESSAGE_ERROR: "NEW_MESSAGE_ERROR",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    DELETE_MESSAGE_SUCCESS: "DELETE_MESSAGE_SUCCESS",
    DELETE_MESSAGE_ERROR: "DELETE_MESSAGE_ERROR",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    UPDATE_MESSAGE_SUCCESS: "UPDATE_MESSAGE_SUCCESS",
    UPDATE_MESSAGE_ERROR: "UPDATE_MESSAGE_ERROR",
    JOIN_ROOM: "JOIN_ROOM",
    JOIN_ROOM_SUCCESS: "JOIN_ROOM_SUCCESS",
    LEAVE_ROOM: "LEAVE_ROOM",
    LEAVE_ROOM_SUCCESS: "LEAVE_ROOM_SUCCESS",
    ROOM_ERROR: "ROOM_ERROR",
  },
};

module.exports = CONSTANTS;
